/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=WorkerEnv` (hash: 46cce289db04eada5136024deb568be0)
interface __BaseEnv_WorkerEnv {
	TIDEBOT_WEBHOOK_QUEUE: Queue;
	TIDEBOT_APP_ID: string;
	TIDEBOT_PRIVATE_KEY: string;
	TIDEBOT_WEBHOOK_SECRET: string;
	TIDEBOT_ALLOWED_OWNERS: string;
	TIDEBOT_WEBHOOK_DELIVERIES: DurableObjectNamespace<import("./src/runtime/worker").WebhookDelivery>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/runtime/worker");
		durableNamespaces: "WebhookDelivery";
	}
	interface PreviewEnv {
		TIDEBOT_WEBHOOK_QUEUE: Queue;
		TIDEBOT_APP_ID: string;
		TIDEBOT_PRIVATE_KEY: string;
		TIDEBOT_WEBHOOK_SECRET: string;
		TIDEBOT_ALLOWED_OWNERS: string;
		TIDEBOT_WEBHOOK_DELIVERIES: DurableObjectNamespace<import("./src/runtime/worker").WebhookDelivery>;
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TIDEBOT_APP_ID" | "TIDEBOT_PRIVATE_KEY" | "TIDEBOT_WEBHOOK_SECRET" | "TIDEBOT_ALLOWED_OWNERS">> {}
}
