name: Probe
on: push
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: read
  actions: write
  deployments: read

jobs:
  probe:
    uses: ./.github/workflows/run.yml
    secrets:
      app_id: ${{ secrets.TIDEBOT_APP_ID }}
      private_key: ${{ secrets.TIDEBOT_PRIVATE_KEY }}
